#include <USRefl/USRefl.h>

// Point's definition
// and Point's reflection declaration (Point_AutoRefl.inl, generated by CMake before building)
#include "Point.h"

#include <iostream>

using namespace Ubpa::USRefl;
using namespace std;

int main() {
	cout << TypeInfo<Point>::name << endl;

	TypeInfo<Point>::fields.ForEach([](auto field) {
		cout << field.name << endl;
		field.attrs.ForEach([](auto attr) {
			cout << attr.name;
			if constexpr (attr.has_value)
				cout << " : " << attr.value;
			cout << endl;
		});
	});

	constexpr auto y_idx = TypeInfo<Point>::fields.Find("y");
	constexpr auto y_field = TypeInfo<Point>::fields.Get<y_idx>();
	static_assert(y_field.name == "y");

	static_assert(TypeInfo<Point>::fields.Contains("x"));

	TypeInfo<Point>::attrs.ForEach([](auto attr) {
		cout << "name  : " << attr.name << endl;
		if constexpr (!attr.has_value)
			cout << "value : " << attr.value << endl;
	});

	TypeInfo<Point>::ForEachVarOf(Point{ 1,2 }, [](auto&& var) {
		cout << var << endl;
	});
}
