// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<typename T>
struct Ubpa::USRefl::TypeInfo<Ubpa::Nested::Vec<T>>
    : Ubpa::USRefl::TypeInfoBase<Ubpa::Nested::Vec<T>>
{
    static constexpr AttrList attrs = {
        Attr{"size", sizeof(T)},
    };

    static constexpr FieldList fields = {
        Field{"x", &Ubpa::Nested::Vec<T>::x,
            AttrList{
                Attr{"not_serialize"},
            }
        },
        Field{"y", &Ubpa::Nested::Vec<T>::y,
            AttrList{
                Attr{"info", "hello"},
                Attr{"maximum", 10.f},
            }
        },
        Field{"num", &Ubpa::Nested::Vec<T>::num},
        Field{Name::constructor, WrapConstructor<Ubpa::Nested::Vec<T>()>()},
        Field{Name::constructor, WrapConstructor<Ubpa::Nested::Vec<T>(T, T)>(),
            AttrList {
                Attr{UBPA_USREFL_NAME_ARG(0),
                    AttrList{
                        Attr{Name::name, "x"},
                    }
                },
                Attr{UBPA_USREFL_NAME_ARG(1),
                    AttrList{
                        Attr{Name::name, "y"},
                    }
                },
            }
        },
        Field{Name::destructor, WrapDestructor<Ubpa::Nested::Vec<T>>()},
        Field{"Sum", static_cast<float(Ubpa::Nested::Vec<T>::*)()const>(&Ubpa::Nested::Vec<T>::Sum)},
        Field{"Sum", static_cast<float(Ubpa::Nested::Vec<T>::*)(float)const>(&Ubpa::Nested::Vec<T>::Sum),
            AttrList {
                Attr{UBPA_USREFL_NAME_ARG(0),
                    AttrList{
                        Attr{Name::name, "z"},
                        Attr{"Name::default_value", 1.f},
                    }
                },
            }
        },
        Field{"Dot", &Ubpa::Nested::Vec<T>::Dot,
            AttrList {
                Attr{UBPA_USREFL_NAME_ARG(0),
                    AttrList{
                        Attr{Name::name, "lhs"},
                    }
                },
                Attr{UBPA_USREFL_NAME_ARG(1),
                    AttrList{
                        Attr{Name::name, "rhs"},
                    }
                },
            }
        },
    };
};

