// This file is generated by Ubpa::USRefl::AutoRefl

#pragma once

#include <USRefl/USRefl.h>

template<>
struct Ubpa::USRefl::TypeInfo<A>
    : Ubpa::USRefl::TypeInfoBase<A>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"a", &A::a},
    };
};

template<>
struct Ubpa::USRefl::TypeInfo<B>
    : Ubpa::USRefl::TypeInfoBase<B, Base<A>>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"b", &B::b},
    };
};

template<>
struct Ubpa::USRefl::TypeInfo<C>
    : Ubpa::USRefl::TypeInfoBase<C, Base<A>>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"c", &C::c},
    };
};

template<>
struct Ubpa::USRefl::TypeInfo<D>
    : Ubpa::USRefl::TypeInfoBase<D, Base<B>, Base<C>>
{
    static constexpr AttrList attrs = {};

    static constexpr FieldList fields = {
        Field{"d", &D::d},
    };
};

